fix NPE on Convert to CDF; add "shared test" infrastructure; add test
BrightSpots/rcv pull request #707
Opened 2023-06-16 15:56 UTC by artoonie

Closes #703
Also makes progress towards #692 (but doesn't fully address)

1. Fix the NPE
2. Add two tests, one for Dominion and one for CDF
3. Built a small built of scaffolding in preparation of shared CVRs and config files across tests

2023-06-18 18:01 UTC, HEdingfield requested changes

2023-06-18 21:48 UTC, artoonie commented on src/test/java/network/brightspots/rcv/TabulatorTests.java
> +  }
Yep -- easier to add in #708 so I've added it there.

2023-06-18 21:48 UTC, artoonie commented on src/test/resources/network/brightspots/rcv/test_data/convert_to_cdf_from_cdf/convert_to_cdf_from_cdf_expected_cvr_cdf.json
> +{
They share the config with other tests (as noted above)

2023-06-19 05:30 UTC, HEdingfield commented on src/test/resources/network/brightspots/rcv/test_data/_shared/cdf_json/cdf_json_config.json
> +      "filePath" : "cdf_json_file1_cvr.json",
Ok, I can see that; it just seems to me like it makes the testing infrastructure less straightforward and a bit more opaque for the sake of saving 2 or 3 small config files. I'm ok with whatever you decide though.

2023-06-19 14:13 UTC, artoonie commented on src/test/resources/network/brightspots/rcv/test_data/_shared/cdf_json/cdf_json_config.json
> +      "filePath" : "cdf_json_file1_cvr.json",
Fair enough -- it does simplify the code not using shared configs, and avoids the race condition.

I've removed the config files from _shared and put them with each test.

2023-06-19 14:13 UTC, artoonie commented on src/test/java/network/brightspots/rcv/TabulatorTests.java
> +    runConvertToCdfTest("convert_to_cdf_from_dominion", "dominion_alaska");
Nice -- in fixing this, also realized they weren't being marked as read-only, so addressed that too.

2023-06-19 17:27 UTC, HEdingfield commented on src/test/resources/network/brightspots/rcv/test_data/_shared/cdf_json/cdf_json_config.json
> +      "filePath" : "cdf_json_file1_cvr.json",
SGTM -- it looks like this config is still in the shared directory though. Was this an oversight?

2023-06-19 17:27 UTC, HEdingfield commented on src/test/java/network/brightspots/rcv/TabulatorTests.java
> +    runConvertToCdfTest("convert_to_cdf_from_dominion", "dominion_alaska");
Good point!

2023-06-19 18:32 UTC, artoonie commented on src/main/java/network/brightspots/rcv/TabulatorSession.java
> +        Logger.severe("Failed to set up logging.");
Was trying to avoid an extra indent level -- alas :) made this mirror `tabulate`

2023-06-19 18:33 UTC, artoonie commented on src/test/resources/network/brightspots/rcv/test_data/_shared/cdf_json/cdf_json_config.json
> +      "filePath" : "cdf_json_file1_cvr.json",
oversight!

2023-06-20 05:13 UTC, HEdingfield approved these changes
Added some more logging and simplified it a bit. Great work on this one!

2023-06-20 05:13 UTC, HEdingfield commented on src/main/java/network/brightspots/rcv/TabulatorSession.java
> +        Logger.severe("Failed to set up logging.");
I do think it's a bit weird that setting up this logging says "Tabulation logging to:..." and creates a file called something like `2023-06-19_22-07-23_audit_0.log` even though it's just a CVR-to-CDF conversion, but I guess there's no real harm in doing this.

CC: @tarheel @chughes297 just as a heads-up (CVR to CDF conversions now generate audit logs).

2023-06-20 05:16 UTC, merged